### ISSUE TITLE
Support for Server-Sent Events (SSE)?

### ISSUE THREAD

**Issue by boramalper** [python-hyper/h11#128]
Hi there,

I love using h11 but I couldn't find if it supports [Server-Sent Events (SSE)](https://en.wikipedia.org/wiki/Server-sent_events) in server mode. If not, what is the best way to approach this?

**Comment by njsmith** [comment]
Server-Sent Events don't require anything special from h11 -- they're just a regular server reply that happens to contain data in a certain format: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#event_stream_format

So if you're using h11 directly, you'd just send a stream of `h11.Data` blocks that together make up the SSE text stream. Or if you're using a higher-level interface like hypercorn, then you'd just stream out a response body however your API exposes that.

**Comment by pgjones** [comment]
[Here](https://gitlab.com/pgjones/quart/-/blob/master/examples/broadcast/broadcast.py) is an example using Quart, which uses the aforementioned Hypercorn.
