### ISSUE TITLE
Speed up with Cython

### ISSUE THREAD

**Issue by abersheeran** [python-hyper/h11#131]
On the premise of keeping Pure-Python h11, maybe `.pxd` + `Cython` can be used to improve performance?

Related links: https://cython.readthedocs.io/en/stable/src/tutorial/pure.html#augmenting-pxd

**Comment by pgjones** [comment]
I think Cython is a step too far, I'm having [some success with mypyc though](https://github.com/mypyc/mypyc/issues/701) - I just need to clean it up and propose as a PR.

**Comment by abersheeran** [comment]
> I think Cython is a step too far, I'm having [some success with mypyc though](https://github.com/mypyc/mypyc/issues/701) - I just need to clean it up and propose as a PR.

mypyc also seems to be very good.
