### ISSUE TITLE
Link to docs

### ISSUE THREAD

**Issue by akash5100** [python-hyper/h11#147]
I think, there should be a [link to the documentation](https://h11.readthedocs.io/en/latest/) in the About section of the project on [python-hyper/h11](https://github.com/python-hyper/h11).

**Comment by Kriechi** [comment]
Is the docs badge and the `It also has [a fine manual](https://h11.readthedocs.io/).` line not enough?

**Comment by akash5100** [comment]
Well, this is only a suggestion, for example:

### h2
![Screenshot from 2022-05-02 09-50-21](https://user-images.githubusercontent.com/53405133/166183983-f7a4bcba-f679-43c8-8d37-c3b90e5eb3e9.png)

### h11
![Screenshot from 2022-05-02 09-50-32](https://user-images.githubusercontent.com/53405133/166183998-fffdced7-cf18-4f19-bfc0-94b752116dda.png)

**Comment by Kriechi** [comment]
@akash5100 thanks - I added it!
