### ISSUE TITLE
Question about h11 Dependency in standard mode

### ISSUE THREAD

**Issue by Judekeyser** [python-hyper/h11#160]
Hello,

First of all, thank you for the Uvicorn project, that looks great so far. 

While setting up the library on an existing project, I've observed that the command
```
pip install uvicorn[standard]
```
recommenced in the quick start here : https://www.uvicorn.org/ , actually had a dependency on h11:
```
pip show uvicorn
```
returns
```
Name: uvicorn
Version: 0.21.1
Summary: The lightning-fast ASGI server.
Home-page: 
Author: 
Author-email: Tom Christie <tom@tomchristie.com>
License: 
Location: /usr/local/lib/python3.11/dist-packages
Requires: click, h11
Required-by:
```

If I understand correctly, the Cython-based version (that I should have chosen since I made `[standard]` option), should try to not use `h11` but a lower-level implementation instead (namely, `httptools`).

My question is : why is the dependency on `h11` required in that mode? Is it possible the `h11` library will be chosen at runtime? The documentation states "the http protocol will be handled by httptools if possible.". What does "if possible" means here? How can I make sure about the decision?

I plan to use Uvicorn in a GUnicorn setting, so if I understood correctly the deployment section (https://www.uvicorn.org/deployment/), it should indeed use `httptools` and not `h11`. Is it true?

Sorry if more explanations are provided in some page of the documentation. I couldn't find it.

**Comment by sigmavirus24** [comment]
Why are you asking this project about another project's dependencies?

**Comment by Judekeyser** [comment]
My bad, I got confused !

**Comment by Kludex** [comment]
You need to have httptools installed for uvicorn to use it.
