### ISSUE TITLE
The encoding of the header value does not comply with RFC1945.

### ISSUE THREAD

**Issue by abersheeran** [python-hyper/h11#169]
https://github.com/python-hyper/h11/blob/a2c68948accadc3876dffcf979d98002e4a4ed27/h11/_headers.py#L162

https://github.com/python-hyper/h11/blob/a2c68948accadc3876dffcf979d98002e4a4ed27/h11/_util.py#L127-L135

But in https://datatracker.ietf.org/doc/html/rfc1945#section-2.2

> Recipients of header field TEXT containing octets outside the US-
  ASCII character set may assume that they represent ISO-8859-1
  characters.

**Comment by njsmith** [comment]
Can you be more specific about the problem you see? h11 doesn't handle
character sets at all in header fields, the text you quoted is a
"may", and RFC 1945 has been superseded by multiple generations of
newer RFCs, so it's not clear to me what the issue is...

On Sat, Dec 2, 2023 at 10:42 AM Aber ***@***.***> wrote:
>
> https://github.com/python-hyper/h11/blob/a2c68948accadc3876dffcf979d98002e4a4ed27/h11/_headers.py#L162
>
> https://github.com/python-hyper/h11/blob/a2c68948accadc3876dffcf979d98002e4a4ed27/h11/_util.py#L127-L135
>
> But in https://datatracker.ietf.org/doc/html/rfc1945#section-2.2
>
> Recipients of header field TEXT containing octets outside the US-
> ASCII character set may assume that they represent ISO-8859-1
> characters.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>



-- 
Nathaniel J. Smith -- https://vorpus.org

**Comment by abersheeran** [comment]
```python
import h11

connection = h11.Connection(h11.SERVER)
connection.send(
    h11.Response(status_code=200, headers=[("Host", "example.com"), ("Server", "îá")])
)
```

Using this code can reproduce the issue.

Of course, users can pass [(bytes, bytes)] to Headers. But h11 provides an interface of [(str, str)], does this imply that h11 should be able to handle the encoding correctly here?
