### ISSUE TITLE
MEND Scan returns policy voilation for using bazarr-v1.4.4-beta.9 

### ISSUE THREAD

**Issue by anupy** [python-hyper/h11#179]
Hello, 

MEND Scan returns policy voilation for using `bazarr-v1.4.4-beta.9` for `h11` library, could you please help me resolving the same? 

Does anybody faced this issue before? 

It displays error of using GPL with license https://github.com/morpheus65535/bazarr/blob/v1.4.4-beta.9/LICENSE

**Comment by zanieb** [comment]
As this project has no requirements, I don't see how that could be the case. Do you have more information on how the packages are related?

**Comment by sigmavirus24** [comment]
Mend is a tool you're paying for and which is frequently absolute trash at detecting real issues. Please contact your support contact

**Comment by anupy** [comment]
> Mend is a tool you're paying for and which is frequently absolute trash at detecting real issues. Please contact your support contact

I think so, it's absolultely false positive!
