### ISSUE TITLE
Document docs/source/_static/show-code.js copyright and license

### ISSUE THREAD

**Issue by sdelafond** [python-hyper/h11#61]
Hello,
while packaging python-h11 in Debian, we noticed there was no clear copyright/license for this file, except for:

    // Stolen from statsmodels and fixed up

Could you document exactly where this is coming from, and what the copyright/license is, so I can include this information where needed ?

Cheers,

--Seb

**Comment by njsmith** [comment]
Oh, heh, nice catch!

It looks like that was originally written by @jseabold and contributed to statsmodels, in this commit: https://github.com/statsmodels/statsmodels/commit/24c850c62fd1716ca070a03b35734c71b2ffcae1#diff-01b20d9015b8f6f5ab9a901553c96a51

So I guess that means it's [licensed under BSD3](https://github.com/statsmodels/statsmodels/blob/master/LICENSE.txt).

This most recently came from my project [patsy](https://github.com/pydata/patsy), but I guess the Debian devs managing the python-patsy package missed it.

**Comment by sdelafond** [comment]
Awesome, thanks for the quick answer. I've documented it as such:

> Files: docs/source/_static/show-code.js
> Copyright: 2012 Statsmodels Developers
> License: BSD-3

**Comment by njsmith** [comment]
Excellent.

If it's too much trouble then no worries, but -- would you mind submitting a PR to add the proper boilerplate to `show-code.js` too, so that the official releases are properly license-compliant, not just the debian repackaging?
