### ISSUE TITLE
h11 does not distinguish between bytearray and bytestrings in equality tests

### ISSUE THREAD

**Issue by DaanDeMeyer** [python-hyper/h11#63]
In Python 2 and 3 `bytearray(b'host') == b'host'` is `True`. This results in issues like #60 where users of h11 end up with bytearray's instead of bytestrings. The tests in h11 don't catch these issues because they themselves rely on the python equality operator which returns True when comparing bytearrays and bytestrings that contain the same string.

This can be solved by changing the equality checks to require corresponding fields in both classes to be the same type instead of just checking for equality. I implemented this locally but it broke a lot of tests (since they all assume bytestring == bytearray) so I'm raising the issue here before going forward with fixing them all.

As an example of why bytestrings and bytearrays are not interchangeable: bytestring can be used as a dictionary key but bytearray can not (since it is mutable).

**Comment by njsmith** [comment]
#64 adds a test that when we return headers, we always do so as `bytes`. What other kinds of issues are you worried about?

**Comment by DaanDeMeyer** [comment]
Looking at the broken tests (after implementing a more strict equality test), It seems the `data` field in `Data` suffers from the same problem where all the expected results in the tests work with bytestrings but the actual values are bytearrays. 

Looking at the code, this is because `ReceiveBuffer` works with a bytearray but the fields are never converted to bytestrings before being passed to the `Data` constructor. If the intention is to expose data as bytestrings I'd make sure the `data` field in `Data` is always exposed as a bytestring as well.

**Comment by njsmith** [comment]
Converting from bytearray to bytes isn't free, so it's nice if we can skip
it. Given that we've always returned bytearray there, and that Data chunks
don't make any sense as dict keys, maybe we should just leave that one as
is.

**Comment by DaanDeMeyer** [comment]
That makes sense. However, wouldn't it still be beneficial then to have stricter equality checking for events and switch all the tests involving `Data` to use bytearray's so similar issues are avoided? I can make a pr to implement the stricter equality check along with fixing the tests.

**Comment by DaanDeMeyer** [comment]
Actually, thinking more about it that would probably be too complex. Verifying the headers are returned as bytes is a good short-term solution.

**Comment by njsmith** [comment]
Sounds like this can be closed then, at least for now.
