### ISSUE TITLE
h11.Response() doesn't honor IntEnum status_code 

### ISSUE THREAD

**Issue by belm0** [python-hyper/h11#72]
e.g. `h11.Response(status_code=HTTPStatus.NOT_FOUND)` yields a 200 status

it appears that `str()` is being used on the value

https://github.com/python-hyper/h11/blob/5a976c938204be494b243d2653a70b28fae17b58/h11/_writers.py#L54

**Comment by njsmith** [comment]
Wow, that's tricky.

We already validate that `isinstance(status_code, int)`... but of course that doesn't help.

The official safe way to coerce to int is `operator.index`... but that passes through `HTTPStatus` objects unchanged.

At least `int(HTTPStatus.NOT_FOUND)` actually does the right thing.

I guess we should do `isinstance` *and* coerce using `int`? (In `_EventBundle.__init__`)

**Comment by belm0** [comment]
would `("%d" % response.status_code).encode("ascii")` in the cited code be enough?

**Comment by njsmith** [comment]
That seems reasonable too. I guess the main difference is whether anyone looking at `event.status_code` in the mean time sees an `int` or an `HTTPStatus`. I'm a little nervous about having a non-`int` object there since all the code was written on the assumption that it's an `int`, but of course `IntEnum` is compatible with `int` so it should be fine right? ...maybe?

**Comment by belm0** [comment]
I'm tending to agree that the library should covert at entry-- it seems too error prone for something in the implementation to accidentally start using str(), `%s`, etc. on one of these objects.

The implication for library authors isn't good:  basically every API accepting integer codes needs to be defensive like this.  IntEnum is the closest thing to a grenade I've seen in Python.

**Comment by shaolo1** [comment]
I actually tripped over this recently using quart [](https://github.com/pgjones/quart/issues/29)  I didn't realize at the time I submitted the issue that it was h11

**Comment by njsmith** [comment]
See #77 for a fix.
