### ISSUE TITLE
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:852)

### ISSUE THREAD

**Issue by freis** [python-hyper/h11#91]
I've been having this issue when I use any package that uses h11 and I'm wondering if it has something to do with h11 and not the packages.
This is the example that I've raised with httpx: https://github.com/encode/httpx/issues/646
My main issue is seeing that when I use http://ip:port then if a website does a redirect the port is being pushed into the Location and if I use a curl to test everything works ok and that port is not in the Location.

**Comment by njsmith** [comment]
This seems to be an httpx bug, not an h11 bug (see my comment on that issue), so closing this. If that changes we can always re-open it :-)

**Comment by freis** [comment]
Thanks for your input on that ;)
